### ISSUE TITLE
Installation issue and xss issue with dom based challenge on the portswigger acadamy

### ISSUE THREAD

**Issue by zflemingg1** [fcavallarin/domdig#5]
Hello!

I think I am having issues with installation. 

johnd@kali:~/Github$ cd domdig && npm i && cd ..

> puppeteer@1.20.0 install /home/johnd/Github/domdig/node_modules/puppeteer
> node install.js

Downloading Chromium r686378 - 114 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/johnd/Github/domdig/node_modules/puppeteer/.local-chromium/linux-686378
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN The package htcrawl is included as both a dev and production dependency.

added 52 packages from 27 contributors and audited 60 packages in 22.961s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

I also tested it against https://portswigger.net/web-security/cross-site-scripting/dom-based/lab-document-write-sink and it doesn't appear to be working. Not sure if I'm doing something wrong?

**Comment by fcavallarin** [comment]
according to your output, the installation seems to be ok. 
The link you provided is authenticated, so I cannot check it.
