### ISSUE TITLE
How to Config Tool to Manually Login

### ISSUE THREAD

**Issue by nxenon** [fcavallarin/domdig#9]
I saw that this tool uses config like this to login:
```
[
   ["navigate", "https://target.local/login-page"],
   ["write", "#username", "demo"],
   ["write", "#password", "demo"],
   ["sleep", 2],
   ["clickToNavigate", "#btn-login"]
]
```

But how can I manually login in the page when the page gets opened. For example the page has captcha and I have to put it manually in the captcha field.

**Comment by fcavallarin** [comment]
This is not possible at the moment. It's going to be implemented in the upcoming release.
The login sequence is meant to automate logins, if the login requires some manual intervention, you'd better set the authentication token(s) in the headers/cookies/localStorage ..
